name: Legal System CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: [self-hosted, windows, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.2'

      - name: Create venv, install dependencies
        shell: powershell
        run: |
          python -m venv .venv
          .venv\Scripts\activate.ps1
          python -m pip install --upgrade pip
          pip install -r requirements.txt