name: Legal System CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: [self-hosted, windows, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.2'
      
      - name: Create and activate virtual environment
        run: |
          python -m venv .venv
          .venv\Scripts\activate
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run tests
      #   run: |
      #     # The command to run your tests goes here.
      #     # For example, if you use pytest:
      #     pip install pytest
      #     pytest